services:
  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: crowdsec
    restart: unless-stopped
    volumes:
      - ./crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
      - /var/log:/var/log:ro
      - /root/crowdsec/data:/var/lib/crowdsec/data/
      - /root/crowdsec/config:/etc/crowdsec/