services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Canada/Pacific
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - /home/localusr/docker/overseerr/config:/app/config
    restart: unless-stopped