# Docker Compose file to deploy Syncthing
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: ubuntu_docker #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Canada/Pacific
    volumes:
      - /home/localusr/docker/syncthing/config:/config
      - /home/localusr/docker/plex/media/Movies:/Movies
      - /home/localusr/docker/plex/media/Shows:/Shows
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
