services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Canada/Pacific
    volumes:
      - /home/localusr/docker/radarr/data:/config
      - /home/localusr/docker/plex/media/Movies:/movies #optional
      - /home/localusr/Downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
